### PR TITLE
Bump build number to rebuild osx-64

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

[osx-64 build failed](https://github.com/conda-forge/fisx-feedstock/runs/24883570607) when merging into main because libcxx was updated from 16.x.x to 17.x.x between the time of the MR and the merge. libcxx 17.x.x requires MacOS >=10.13 (see https://github.com/conda-forge/libcxx-feedstock/pull/131)

My understanding is that a re-render should fix it due to https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5829

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
Thanks for merging https://github.com/conda-forge/fisx-feedstock/pull/20 @tschoonj !

Unfortunately I saw that the osx-64 build failed. This is because libcxx was updated to 17.x.x in the meantime and that required a re-render to increase the minimum macOS deployment target to 10.13.
This is what I did in this PR.

**Review by tschoonj — APPROVED** [review]
LGTM

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
Travis CI is not very reliable and really slow.
 Trying to switch to azure and cross-compiling for linux aarch64 and ppcle64

**Comment by beenje** [comment]
@tschoonj the move to azure for linux aarch64 and ppcle64 went well.
I think that will improve the pipeline. Ready to be merged again.

**Pull request merged**
